# Generated by Django 5.0.6 on 2024-06-24 07:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=20)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_id', models.CharField(blank=True, max_length=5, null=True)),
                ('elevation', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'junctions',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material', models.CharField(choices=[('PE100', 'PE100'), ('STEEL', 'STEEL'), ('STAINLESS_STEEL', 'STAINLESS STEEL'), ('CI', 'CI'), ('NA', 'NA')], default='PE100', max_length=15)),
                ('type', models.CharField(choices=[('PIPE', 'PIPE'), ('VALVE', 'VALVE'), ('FITTING', 'FITTING'), ('STRAINER', 'STRAINER'), ('DISMANTLING_JOINT', 'DISMANTLING JOINT'), ('OTHER', 'OTHER')], default='OTHER', max_length=17)),
                ('pn', models.CharField(choices=[('8', '8'), ('10', '10'), ('16', '16'), ('20', '20'), ('25', '25'), ('40', '40'), ('63', '63'), ('NA', 'NA')], default='NA', max_length=17)),
                ('dn', models.IntegerField(null=True)),
                ('od', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feature', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['material', 'dn'],
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
