# Generated by Django 5.0.6 on 2024-09-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PE100', 'PE100'), ('STEEL', 'STEEL'), ('STAINLESS_STEEL', 'STAINLESS STEEL'), ('CI', 'CI'), ('NA', 'NA')], default='PE100', max_length=15)),
                ('type', models.CharField(choices=[('PIPE', 'PIPE'), ('VALVE', 'VALVE'), ('FITTING', 'FITTING'), ('STRAINER', 'STRAINER'), ('DISMANTLING_JOINT', 'DISMANTLING JOINT'), ('OTHER', 'OTHER')], default='OTHER', max_length=17)),
                ('dn', models.IntegerField(null=True)),
                ('pn', models.CharField(choices=[('8', '8'), ('10', '10'), ('16', '16'), ('20', '20'), ('25', '25'), ('40', '40'), ('65', '65'), ('NA', 'NA')], default='NA', max_length=3)),
                ('decl_no', models.CharField(max_length=7)),
                ('seller', models.CharField(max_length=30)),
                ('truck', models.CharField(max_length=12)),
                ('invoice', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('measure', models.CharField(choices=[('PCS', 'PCS'), ('M', 'M'), ('KG', 'KG')], default='PCS', max_length=5)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='EUR', max_length=3)),
            ],
            options={
                'db_table': 'purchase',
                'ordering': ['material', 'dn'],
            },
        ),
        migrations.AlterField(
            model_name='materials',
            name='pn',
            field=models.CharField(choices=[('8', '8'), ('10', '10'), ('16', '16'), ('20', '20'), ('25', '25'), ('40', '40'), ('65', '65'), ('NA', 'NA')], default='NA', max_length=17),
        ),
    ]
