# Generated by Django 5.0.6 on 2024-09-25 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchase_alter_materials_pn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
