# Generated by Django 5.0.6 on 2024-09-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('PIPE', 'PIPE'), ('VALVE', 'VALVE'), ('FITTING', 'FITTING'), ('STRAINER', 'STRAINER'), ('PUMP', 'PUMP'), ('DISMANTLING_JOINT', 'DISMANTLING JOINT'), ('OTHER', 'OTHER')], default='OTHER', max_length=17),
        ),
    ]
