# Generated by Django 5.0.6 on 2024-09-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_purchase_currency_alter_purchase_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='truck',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
