# Generated by Django 5.0.6 on 2024-09-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_junctions_delete_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='quantity',
            new_name='qty',
        ),
    ]
