# Generated by Django 5.0.6 on 2024-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_purchase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='decl_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='inv_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
