# Generated by Django 5.0.6 on 2024-09-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_purchase_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
