# Generated by Django 5.0.6 on 2024-09-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_purchase_decl_date_purchase_inv_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='decl_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='inv_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
