import Header from '@/components/header/header';
import './globals.css';
import AuthProvider from '@/components/AuthProvider/AuthProvider';

export const metadata = {
  title: 'GZA AWA',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <header>
            <Header />
          </header>
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
