import Image from 'next/image';
import Logo from '../../public/images/chuck.png';
import Header from '@/components/header/Header';

export const metadata = {
  title: 'GZA AWA',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          
          <Header/>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
